package com.devconnect.interceptors.graphql

import com.apollographql.apollo3.api.ApolloRequest
import com.apollographql.apollo3.api.ApolloResponse
import com.apollographql.apollo3.api.Operation
import com.apollographql.apollo3.interceptor.ApolloInterceptor
import com.apollographql.apollo3.interceptor.ApolloInterceptorChain
import com.devconnect.DevConnect
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.onCompletion
import kotlinx.coroutines.flow.onEach

/**
 * Apollo Kotlin `ApolloInterceptor` that emits `client:graphql_*` events
 * to the desktop State Inspector / Network Inspector.
 *
 * Wire it into the Apollo client:
 * ```kotlin
 * val apollo = ApolloClient.Builder()
 *     .serverUrl("https://api.example.com/graphql")
 *     .addInterceptor(DevConnectApolloInterceptor())
 *     .build()
 * ```
 *
 * Spec (Round 3 / 3.1):
 *  - On `intercept(request, chain)`: parse `request.operation.name()`
 *    and `request.operation.variables()` → emit `client:graphql_operation`.
 *  - On response: emit `client:graphql_response { operation, latencyMs,
 *    cacheHit: response.extensions["persistedQuery"] != null, errors: [...] }`.
 *
 * Notes:
 *  - Apollo Kotlin 3.x has a unified Flow-based interceptor API (no
 *    `onResponse`/`onFetchError` callbacks). We wrap `chain.proceed(...)`
 *    with `onEach`/`onCompletion` operators to capture timing + errors.
 *  - `Operation.variables()` is generated by the Apollo Gradle plugin and
 *    not part of the public `Operation` interface; we read it via
 *    reflection so generated queries/mutations work without us knowing
 *    the concrete subclass.
 */
class DevConnectApolloInterceptor : ApolloInterceptor {
    override fun <D : Operation.Data> intercept(
        request: ApolloRequest<D>,
        chain: ApolloInterceptorChain,
    ): Flow<ApolloResponse<D>> {
        val startTime = System.currentTimeMillis()
        val operation = request.operation
        val operationName = operation.name()
        val operationType = operation.javaClass.simpleName // Query / Mutation / Subscription
        val variables = readVariables(operation)

        try {
            DevConnect.safeSend("client:graphql_operation", mapOf(
                "operation" to operationName,
                "type" to operationType,
                "variables" to variables,
            ))
        } catch (_: Throwable) {}

        return chain.proceed(request)
            .onEach { response ->
                try {
                    val cacheHit = response.extensions?.get("persistedQuery") != null
                    val errorsList = response.errors
                    val errorsPayload: List<Map<String, Any>>? = if (!errorsList.isNullOrEmpty()) {
                        errorsList.map { err ->
                            val locs: List<Map<String, Any>> = err.locations?.map { loc ->
                                mapOf("line" to loc.line, "column" to loc.column)
                            } ?: emptyList()
                            mapOf(
                                "message" to (err.message ?: ""),
                                "locations" to locs,
                            )
                        }
                    } else null
                    DevConnect.safeSend("client:graphql_response", buildMap<String, Any?> {
                        put("operation", operationName)
                        put("type", operationType)
                        // Captured at intercept(), not a fresh `now - 0`.
                        put("latencyMs", System.currentTimeMillis() - startTime)
                        put("cacheHit", cacheHit)
                        if (errorsPayload != null) put("errors", errorsPayload)
                    })
                } catch (_: Throwable) {}
            }
            .onCompletion { cause ->
                if (cause != null) {
                    try {
                        DevConnect.safeSend("client:graphql_response", buildMap<String, Any?> {
                            put("operation", operationName)
                            put("type", operationType)
                            put("latencyMs", System.currentTimeMillis() - startTime)
                            put("error", cause.message)
                            put("stack", cause.stackTraceToString())
                        })
                    } catch (_: Throwable) {}
                }
            }
    }

    /**
     * Read generated `variables()` from the Apollo Kotlin `Operation`
     * subclass without depending on the codegen output. Returns an empty
     * map if the generated API isn't there (pure runtime Apollo, mocks,
     * or test fakes).
     */
    private fun readVariables(operation: Operation<*>): Map<String, String?> {
        return try {
            val cls = operation.javaClass
            // Generated subclasses expose a no-arg `variables()` method
            // returning a `com.apollographql.apollo3.api.Executable.Variables`.
            val m = cls.methods.firstOrNull { it.name == "variables" && it.parameterCount == 0 }
                ?: return emptyMap()
            val variables = m.invoke(operation) ?: return emptyMap()
            val valueMapMethod = variables.javaClass.methods
                .firstOrNull { it.name == "getValueMap" && it.parameterCount == 0 }
                ?: return emptyMap()
            @Suppress("UNCHECKED_CAST")
            val rawMap = valueMapMethod.invoke(variables) as? Map<String, Any?>
                ?: return emptyMap()
            rawMap.mapValues { it.value?.toString() }
        } catch (_: Throwable) {
            emptyMap()
        }
    }
}
