name: devconnect_flutter
description: DevConnect client SDK for Flutter - auto-intercepts HTTP, logs, state, storage. Works with Dio, http, Firebase, OAuth2, logger, talker, fimber, and more.
version: 1.0.0
homepage: https://github.com/ridelinktechs/devconnect
repository: https://github.com/ridelinktechs/devconnect
issue_tracker: https://github.com/ridelinktechs/devconnect/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  device_info_plus: ^11.0.0

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
